import type { Metadata } from "next";
import "./globals.css";

import { Fira_Code } from "next/font/google";
import Navbar from "./component/Navbar";
import { useDeveloperInfo } from "./actions/useDeveloperInfo";

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fira-code",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Eng Bunseu - Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const config = await useDeveloperInfo();
  return (
    <html lang="en">
      <body className={`${firaCode.variable} antialiased `}>
        <div id="root">
          <div className="flex flex-col h-full">
            <Navbar config={config} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
